import { createPost } from "@/app/actions";
import { Header } from "@/components/Header";
import { categories } from "@/lib/mock-data";
import { hasSupabaseEnv } from "@/lib/supabase";

export default async function CreatePostPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const { error } = await searchParams;
  return (
    <main><Header /><section className="mx-auto max-w-3xl px-4 py-10"><div className="rounded-3xl border border-stone-200 bg-white p-6 paper-shadow md:p-8"><p className="text-sm font-bold uppercase tracking-wide text-amber-700">Yeni kayıt</p><h1 className="mt-2 text-3xl font-black text-stone-950">İlan veya duvar yazısı bırak</h1><p className="mt-3 text-stone-600">İlanlar anonim yayınlanır. Telefon, e-posta ve gerçek ad alanı istemiyoruz; cevaplaşma sistem içinden ilerler.</p>{!hasSupabaseEnv() && <div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">Kayıt yapabilmek için önce <code className="rounded bg-amber-100 px-1">.env.local</code> içine Supabase URL ve anon key eklenmeli.</div>}{error && <div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-900">İlan kaydedilemedi. Bilgileri kontrol edip tekrar deneyin.</div>}<form action={createPost} className="mt-8 grid gap-5"><label className="grid gap-2 text-sm font-semibold text-stone-800">Tür<select name="type" className="rounded-xl border border-stone-300 px-4 py-3" defaultValue="ilan"><option value="ilan">İlan</option><option value="duvar-yazisi">Duvar Yazısı</option></select></label><label className="grid gap-2 text-sm font-semibold text-stone-800">Kategori<select name="category" className="rounded-xl border border-stone-300 px-4 py-3">{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold text-stone-800">Başlık<input name="title" required minLength={3} className="rounded-xl border border-stone-300 px-4 py-3" placeholder="Örn. Bina girişinde anahtar bulundu" /></label><label className="grid gap-2 text-sm font-semibold text-stone-800">Mesaj<textarea name="body" required minLength={10} className="min-h-40 rounded-xl border border-stone-300 px-4 py-3" placeholder="Kişisel telefon/e-posta yazmamanızı öneririz. Sistem anonim cevaplaşma sağlayacak." /></label><button type="submit" className="rounded-full bg-stone-950 px-5 py-3 font-bold text-white">Yayınla</button></form></div></section></main>
  );
}
